# Generated by Django 4.1.7 on 2023-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="days_left",
            field=models.IntegerField(default=1),
        ),
    ]
